# Operational Performance Standards

## Performance Charges

```{r message = FALSE, echo = FALSE, error = FALSE, warning = FALSE, fig.width = 12, fig.height = 5}

ops_data_clean_temp %>%
  dplyr::filter(
    Charges > 0
    ) %>%
  tidyr::drop_na(Charges) %>%
  base::droplevels() %>%
  ggplot2::ggplot(
    ggplot2::aes(x = Date, y = Charges, fill = Standard)
    ) + 
  ggplot2::geom_bar(stat = "identity") + 
  ggplot2::theme(
    legend.title = ggplot2::element_blank(),
    text = ggplot2::element_text(size = 15)
    ) +
  ggplot2::scale_y_continuous(
    labels = scales::comma,
    breaks = scales::pretty_breaks(4)
    ) +
  ggplot2::labs(
    title = "Performance Charges",
    subtitle = "Breakdown by month and standard",
    caption = "Source: MOSL"
    ) +
  ggplot2::ylab("Charges (£)") + ggplot2::xlab("")

```

<br>

```{r message = FALSE, echo = FALSE, error = FALSE, warning = FALSE}

# Creating table of charges by OPS ---------------- 

ops_data_clean_temp %>%
  dplyr::filter(
    Date >= data.period %m-% months(11),
    PerformanceMeasure == "Completed",
    Charges > 0
    ) %>%
  tidyr::drop_na(Charges) %>%
  base::droplevels() %>%
  dplyr::select(Date, Standard, Charges) %>%
  dplyr::mutate(Date = format(Date, "%Y-%m")) %>% 
  tidyr::drop_na(Charges) %>%
  base::droplevels() %>%
  tidyr::spread(Standard, Charges) %>%
  dplyr::mutate(
    Total = rowSums(dplyr::select(., -Date), na.rm = TRUE)
    ) %>%
  kableExtra::kable (
    format = "latex", 
    caption = "Breakdown of Charges by Standard", 
    linesep = "",
    format.args = list(big.mark = ","),
    booktabs = TRUE,
    align = "c"
    ) %>%
  kableExtra::kable_styling(
    font_size = 10,
    latex_options = c(
      "repeat_header",
      "hold_position",
      "striped",
      position = "center", 
      full_width = FALSE,
      "scale_down"
      )
    ) %>%
  kableExtra::row_spec(0, bold = TRUE)

```

## On-Time Task Completion and Outstanding Tasks

```{r message = FALSE, echo = FALSE, error = FALSE, warning = FALSE, fig.width = 12, fig.height = 5}

rect_df <- data.frame(
  xmin = rep(min(ops_data_clean_temp$Date), 4), 
  xmax = rep(max(ops_data_clean_temp$Date), 4), 
  ymin = c(0.9, 0.8, 0.7, 0), 
  ymax = c(1, 0.9, 0.8, 0.7), 
  cat = 
    factor(
      c("Very good", "Good", "Poor", "Very poor"), 
      levels = c("Very good", "Good", "Poor", "Very poor")
      )
  )

ops_data_clean_temp %>%
  dplyr::group_by(Date, PerformanceMeasure, Group) %>%
  dplyr::summarise(
    GroupPerf = stats::weighted.mean(Performance, TaskVolume)
    ) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(
    dplyr::filter(
      dplyr::select(
        ops_aggregate_perf_temp, 
        Trading.Party.ID, 
        Date, 
        Agg_Perf_roll,
        PerformanceMeasure
        ), 
      Trading.Party.ID == TRADING.PARTY
      ),
    by = c("Date", "PerformanceMeasure")
    ) %>%
  tidyr::drop_na(GroupPerf) %>%
  droplevels() %>%
  ggplot2::ggplot() + 
  ggplot2::geom_line(
    ggplot2::aes(
      x = Date, 
      y = GroupPerf, 
      colour = Group,
      linetype = Group
      )
    ) +
  ggplot2::geom_line(
    ggplot2::aes(
      x = Date, 
      y = Agg_Perf_roll,
      colour = "Agg. Performance"
      ),
    linetype = "dashed",
    size = 1
    ) +
  ggplot2::geom_rect(
      data = rect_df, 
      ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = cat), 
      alpha = 0.1
      ) +
    ggplot2::scale_fill_manual(
      values = c("green4", "greenyellow", "orange1", "orangered1")
      ) +
  ggplot2::theme(
    legend.title = ggplot2::element_blank(),
    text = ggplot2::element_text(size = 15)
    ) +
  ggplot2::scale_y_continuous(
    breaks = scales::pretty_breaks(4)
    ) +
  ggplot2::labs(
    title = paste0("OPS On-Time Task Completion: ", SHORT.NAME),
    subtitle = "Breakdown by month and standard",
    caption = "Source: MOSL\nNote: Aggregate performance corresponds to the 6-month average of aggregate OPS performance"
    ) +
  ggplot2::ylab("") + ggplot2::xlab("") +
  ggplot2::facet_wrap(~PerformanceMeasure)

```

```{r message = FALSE, echo = FALSE, error = FALSE, warning = FALSE, results = "asis"}

ops_data_clean_temp %>% 
  dplyr::filter(
    Date >= max(ops_data_clean_temp$Date) %m-% months(11),
    PerformanceMeasure == "Completed",
    TaskVolume > 0
    ) %>%
  tidyr::drop_na(TaskVolume) %>%
  base::droplevels() %>%
  dplyr::mutate(
    Performance = format(Performance, digits = 2),
    Date = format(Date, "%Y-%m")
    ) %>%
  dplyr::select(
    Date, Standard, Performance
    ) %>%
  tidyr::drop_na(Performance) %>%
  base::droplevels() %>%
  tidyr::spread(key = Standard, value = Performance) %>%
  kableExtra::kable(
    format = "latex", 
    caption = "OPS On Time Completed Tasks by Month",
    linesep = "",
    format.args = list(big.mark = ","),
    booktabs = TRUE,
    align = "c"
    ) %>%
  kableExtra::kable_styling(
    font_size = 10,
    latex_options = c(
      "repeat_header",
      "hold_position",
      "striped",
      position = "center", 
      full_width = FALSE,
      "scale_down"
      )
    ) %>%
  kableExtra::row_spec(0, bold = TRUE)

```

## Performance Issues

## Analysis

```{r message = FALSE, echo = FALSE, error = FALSE, warning = FALSE, results = "asis", eval = FALSE}

ops_list <- unique(as.character(perf_status_ops_temp$Standard))

res <- lapply(mps_list, function (MPS_CHUNK) {
  
  knitr::knit_child(
    "pfm_report_ops_template.Rmd", envir = environment(), quiet = TRUE
  )
  
})

cat(unlist(res), sep = "\n")

```

## Market Aggregates
